# Generated by Django 4.1.3 on 2022-11-20 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('unidades', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('importe', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nombre', models.CharField(default='Sin Marca asignada', max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('modelo', models.CharField(max_length=30)),
                ('unidades', models.PositiveIntegerField(default=1)),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('detalles', models.CharField(blank=True, default='Sin detalles', max_length=30)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.marca')),
            ],
        ),
    ]
