# Generated by Django 4.1.2 on 2022-10-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
