# Generated by Django 4.1.2 on 2022-10-31 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_marca_id_alter_marca_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='tienda.marca'),
        ),
    ]
